# Use R language
language: r

#Define R-versions
r:
  - release
  - devel

apt_packages:
  - libv8-dev
  - librsvg2-dev

r_github_packages: 
  - r-lib/testthat
  - r-lib/covr

script:
  - Rscript -e "library(testthat); testthat::test_dir('tests/testthat', reporter = "fail")"

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
